h=int(input("Enter the value of height:"))
b=int(input("Enter the value of base:"))
triangle=lambda h,b:(.5*h*b)
print("Area of triangle:",triangle(h,b))
a=int(input("Enter the value of square side:"))
square=lambda a:(a*a)
print("Area of square:",square(a))
b=int(input("Ener the value of base:"))
l=int(input("Enter the value of length:"))
rectangle=lambda b,l:(l*b)
print("Area of recangle:",rectangle(l,b))
